### ISSUE TITLE
Case不会自动刷新了

### ISSUE THREAD

**Issue by lixin-wei** [yuzeming/CEACStatTracker#4]
作者您好，你公网部署的网站，case不会自动刷新了，能麻烦排查一下吗？每次都得上去手动点下Refresh Now才会刷新
比如我这个：<https://track.moyu.ac.cn/detail/630ed784514f53cfbb63f40f>，Case Last Seem已经过去6小时了，但还是没自动更新。

另外能麻烦顺便手动刷新一下近几个月的所有case吗？我估计很多refused都已经是issued了，我想看下还有多少refused。

**Comment by DaveHJT** [comment]
作者您好，确实个人的case没有自动刷新，而且统计数据好像二十多天没啥变化，不知道是不是没有自动刷新的原因

**Comment by yuzeming** [comment]
你能在公众号留言你的CaseNo么，我可以帮你查查日志。
